# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cashflow_day.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(351, 351)
        Frame.setStyleSheet("#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-top-right-radius: 20px ;\n"
"border-top-left-radius: 20px ;\n"
"border-bottom-right-radius: 20px ;\n"
"border-bottom-left-radius: 20px ;\n"
"}")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-30, 280, 401, 51))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_passer_cashflow_day_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_passer_cashflow_day_2.setGeometry(QtCore.QRect(260, 10, 75, 23))
        self.pushButton_passer_cashflow_day_2.setStyleSheet("QPushButton#pushButton_passer_cashflow_day_2{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_passer_cashflow_day_2:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_passer_cashflow_day_2.setObjectName("pushButton_passer_cashflow_day_2")
        self.pushButton_valider_cashflow_day_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_valider_cashflow_day_2.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.pushButton_valider_cashflow_day_2.setStyleSheet("QPushButton#pushButton_valider_cashflow_day_2{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_valider_cashflow_day_2:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_valider_cashflow_day_2.setObjectName("pushButton_valider_cashflow_day_2")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(100, 30, 171, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_cashflow_day = QtWidgets.QLabel(Frame)
        self.label_cashflow_day.setGeometry(QtCore.QRect(60, 130, 231, 91))
        self.label_cashflow_day.setObjectName("label_cashflow_day")
        self.label_marche = QtWidgets.QLabel(Frame)
        self.label_marche.setGeometry(QtCore.QRect(30, 100, 291, 161))
        self.label_marche.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_marche.setText("")
        self.label_marche.setObjectName("label_marche")
        self.label_marche.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.label_cashflow_day.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton_passer_cashflow_day_2.setText(_translate("Frame", "passer"))
        self.pushButton_valider_cashflow_day_2.setText(_translate("Frame", "valider"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:22pt;\">CASHFLOW DAY</span></p></body></html>"))
        self.label_cashflow_day.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">recuperez votre </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">cashflow maintenant</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
