# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charite.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(363, 336)
        Frame.setStyleSheet("\n"
"#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-radius: 20px ;\n"
"}")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-20, 250, 391, 61))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_passer_charite = QtWidgets.QPushButton(self.frame)
        self.pushButton_passer_charite.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.pushButton_passer_charite.setStyleSheet("QPushButton#pushButton_passer_charite{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_passer_charite:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_passer_charite.setObjectName("pushButton_passer_charite")
        self.pushButton_donner_charite = QtWidgets.QPushButton(self.frame)
        self.pushButton_donner_charite.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_donner_charite.setStyleSheet("QPushButton#pushButton_donner_charite{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_donner_charite:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_donner_charite.setObjectName("pushButton_donner_charite")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(100, 10, 161, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_charite = QtWidgets.QLabel(Frame)
        self.label_charite.setGeometry(QtCore.QRect(30, 90, 271, 111))
        self.label_charite.setObjectName("label_charite")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 281, 171))
        self.label_2.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.label_charite.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton_passer_charite.setText(_translate("Frame", "PASSER"))
        self.pushButton_donner_charite.setText(_translate("Frame", "DONNER"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:24pt;\">CHARITE</span></p></body></html>"))
        self.label_charite.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">faites un don de 5000 fcfa </span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">grace à cela pour aurez le </span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">choix de lancer 1, 2 ou 3 </span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">dés jusqu\'à la fin du jeu</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
