# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charite_ft.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(384, 354)
        Frame.setStyleSheet("#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-radius: 30px ;\n"
"}\n"
"")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-20, 270, 421, 51))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_ok_charite_ft = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok_charite_ft.setGeometry(QtCore.QRect(170, 10, 75, 23))
        self.pushButton_ok_charite_ft.setStyleSheet("QPushButton#pushButton_ok_charite_ft{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_ok_charite_ft:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_ok_charite_ft.setObjectName("pushButton_ok_charite_ft")
        self.label_charite_ft = QtWidgets.QLabel(Frame)
        self.label_charite_ft.setGeometry(QtCore.QRect(80, 90, 231, 151))
        self.label_charite_ft.setObjectName("label_charite_ft")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(110, 20, 191, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 311, 191))
        self.label_2.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.frame.raise_()
        self.label_charite_ft.raise_()
        self.label.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton_ok_charite_ft.setText(_translate("Frame", "OK"))
        self.label_charite_ft.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">faites un don de 500 fcfa </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">grace à cela pour aurez le </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">choix de lancer 1, 2 ou 3 </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">dés jusqu\'à la fin du jeu</span></p></body></html>"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:22pt;\">CHARITE FT</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
