# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choix_reve.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(366, 361)
        Frame.setStyleSheet("#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-radius: 30px ;\n"
"}")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(100, 10, 191, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.pushButton_precedent_reve = QtWidgets.QPushButton(Frame)
        self.pushButton_precedent_reve.setGeometry(QtCore.QRect(50, 50, 51, 23))
        self.pushButton_precedent_reve.setStyleSheet("QPushButton#pushButton_precedent_reve{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_precedent_reve:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_precedent_reve.setObjectName("pushButton_precedent_reve")
        self.pushButton_suivant_reve = QtWidgets.QPushButton(Frame)
        self.pushButton_suivant_reve.setGeometry(QtCore.QRect(280, 50, 51, 21))
        self.pushButton_suivant_reve.setStyleSheet("QPushButton#pushButton_suivant_reve{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_suivant_reve:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_suivant_reve.setObjectName("pushButton_suivant_reve")
        self.label_choix_reve = QtWidgets.QLabel(Frame)
        self.label_choix_reve.setGeometry(QtCore.QRect(110, 50, 161, 20))
        self.label_choix_reve.setObjectName("label_choix_reve")
        self.label_profession_choix_reve = QtWidgets.QLabel(Frame)
        self.label_profession_choix_reve.setGeometry(QtCore.QRect(60, 100, 251, 141))
        self.label_profession_choix_reve.setWordWrap(True)
        self.label_profession_choix_reve.setObjectName("label_profession_choix_reve")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-10, 280, 391, 51))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_valider_choix_reve = QtWidgets.QPushButton(self.frame)
        self.pushButton_valider_choix_reve.setGeometry(QtCore.QRect(150, 10, 75, 23))
        self.pushButton_valider_choix_reve.setStyleSheet("QPushButton#pushButton_valider_choix_reve{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_valider_choix_reve:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_valider_choix_reve.setObjectName("pushButton_valider_choix_reve")
        self.label_marche = QtWidgets.QLabel(Frame)
        self.label_marche.setGeometry(QtCore.QRect(40, 90, 291, 161))
        self.label_marche.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_marche.setText("")
        self.label_marche.setObjectName("label_marche")
        self.frame.raise_()
        self.label_marche.raise_()
        self.label.raise_()
        self.pushButton_precedent_reve.raise_()
        self.pushButton_suivant_reve.raise_()
        self.label_choix_reve.raise_()
        self.label_profession_choix_reve.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:20pt;\">CHOIX REVES</span></p></body></html>"))
        self.pushButton_precedent_reve.setText(_translate("Frame", "<<"))
        self.pushButton_suivant_reve.setText(_translate("Frame", ">>"))
        self.label_choix_reve.setText(_translate("Frame", "nom reve"))
        self.label_profession_choix_reve.setText(_translate("Frame", "profession"))
        self.pushButton_valider_choix_reve.setText(_translate("Frame", "valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
