# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controle_fiscale.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(379, 366)
        Frame.setStyleSheet("#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-top-right-radius: 20px ;\n"
"border-top-left-radius: 20px ;\n"
"border-bottom-right-radius: 20px ;\n"
"border-bottom-left-radius: 20px ;\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(70, 20, 271, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_fiscalite = QtWidgets.QLabel(Frame)
        self.label_fiscalite.setGeometry(QtCore.QRect(110, 70, 171, 191))
        self.label_fiscalite.setObjectName("label_fiscalite")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-10, 280, 421, 51))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_ok_fiscalite = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok_fiscalite.setGeometry(QtCore.QRect(150, 10, 75, 23))
        self.pushButton_ok_fiscalite.setStyleSheet("QPushButton#pushButton_ok_fiscalite{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_ok_fiscalite:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_ok_fiscalite.setObjectName("pushButton_ok_fiscalite")
        self.label_marche = QtWidgets.QLabel(Frame)
        self.label_marche.setGeometry(QtCore.QRect(50, 70, 291, 191))
        self.label_marche.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_marche.setText("")
        self.label_marche.setObjectName("label_marche")
        self.label_marche.raise_()
        self.label.raise_()
        self.label_fiscalite.raise_()
        self.frame.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:20pt;\">CONTROLE FISCALE</span></p></body></html>"))
        self.label_fiscalite.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">On a effectué un audit </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">de votre entreprise </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">et vous êtes accusés</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">d\'évasion fiscale</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">vous allez perdre la </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">de votre cash</span></p></body></html>"))
        self.pushButton_ok_fiscalite.setText(_translate("Frame", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
