# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'divorce.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(375, 370)
        Frame.setStyleSheet("#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-top-right-radius: 20px ;\n"
"border-top-left-radius: 20px ;\n"
"border-bottom-right-radius: 20px ;\n"
"border-bottom-left-radius: 20px ;\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(140, 10, 151, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_divorce = QtWidgets.QLabel(Frame)
        self.label_divorce.setGeometry(QtCore.QRect(80, 120, 221, 91))
        self.label_divorce.setObjectName("label_divorce")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-20, 290, 421, 61))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_ok_divorce = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok_divorce.setGeometry(QtCore.QRect(160, 10, 75, 31))
        self.pushButton_ok_divorce.setStyleSheet("QPushButton#pushButton_ok_divorce{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_ok_divorce:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_ok_divorce.setObjectName("pushButton_ok_divorce")
        self.label_marche = QtWidgets.QLabel(Frame)
        self.label_marche.setGeometry(QtCore.QRect(40, 70, 301, 181))
        self.label_marche.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_marche.setText("")
        self.label_marche.setObjectName("label_marche")
        self.label_marche.raise_()
        self.label.raise_()
        self.label_divorce.raise_()
        self.frame.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:22pt;\">DIVORCE</span></p></body></html>"))
        self.label_divorce.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Vous avez divorcé donc vous </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">perdez tous votre cash</span></p></body></html>"))
        self.pushButton_ok_divorce.setText(_translate("Frame", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
