# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'investissement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(354, 359)
        Frame.setStyleSheet("#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-top-right-radius: 20px ;\n"
"border-top-left-radius: 20px ;\n"
"border-bottom-right-radius: 20px ;\n"
"border-bottom-left-radius: 20px ;\n"
"}\n"
"")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-30, 280, 401, 51))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_achetez_investissement = QtWidgets.QPushButton(self.frame)
        self.pushButton_achetez_investissement.setGeometry(QtCore.QRect(80, 10, 75, 23))
        self.pushButton_achetez_investissement.setStyleSheet("QPushButton#pushButton_achetez_investissement{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_achetez_investissement:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_achetez_investissement.setObjectName("pushButton_achetez_investissement")
        self.pushButton_passer_investissement = QtWidgets.QPushButton(self.frame)
        self.pushButton_passer_investissement.setGeometry(QtCore.QRect(260, 10, 75, 23))
        self.pushButton_passer_investissement.setStyleSheet("QPushButton#pushButton_passer_investissement{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_passer_investissement:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_passer_investissement.setObjectName("pushButton_passer_investissement")
        self.label_investissement = QtWidgets.QLabel(Frame)
        self.label_investissement.setGeometry(QtCore.QRect(50, 70, 261, 171))
        self.label_investissement.setWordWrap(True)
        self.label_investissement.setObjectName("label_investissement")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(50, 10, 261, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_marche = QtWidgets.QLabel(Frame)
        self.label_marche.setGeometry(QtCore.QRect(30, 60, 291, 191))
        self.label_marche.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_marche.setText("")
        self.label_marche.setObjectName("label_marche")
        self.label_marche.raise_()
        self.frame.raise_()
        self.label_investissement.raise_()
        self.label.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton_achetez_investissement.setText(_translate("Frame", "Achetez"))
        self.pushButton_passer_investissement.setText(_translate("Frame", "Passer"))
        self.label_investissement.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Faire un investissement</span></p></body></html>"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:22pt;\">INVESTISSEMENT</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
