# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(962, 690)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(-30, -10, 991, 731))
        self.label.setStyleSheet("background-image: url(:/login/loginimage.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(160, 90, 401, 531))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/login/images.jpg);\n"
"image: url(:/login/cashflow.jpg);\n"
"border-radius: 50px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(560, 140, 251, 441))
        self.label_3.setMinimumSize(QtCore.QSize(251, 0))
        self.label_3.setStyleSheet("background : rgba(196, 209, 97, 1);\n"
"border-top-right-radius: 40px;\n"
"border-bottom-right-radius: 40px;")
        self.label_3.setObjectName("label_3")
        self.pushButton_commencer_login = QtWidgets.QPushButton(Frame)
        self.pushButton_commencer_login.setGeometry(QtCore.QRect(610, 480, 141, 41))
        self.pushButton_commencer_login.setStyleSheet("QPushButton#pushButton_commencer_login{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#pushButton_commencer_login:hover{\n"
"    background-color: blue;\n"
"}")
        self.pushButton_commencer_login.setObjectName("pushButton_commencer_login")
        self.lineEdit_2 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 320, 151, 31))
        self.lineEdit_2.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius : 7px;\n"
"padding-bottom: 7px;\n"
"border-bottom: 2px;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(610, 410, 151, 31))
        self.lineEdit_3.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"padding-bottom: 7px;\n"
"border-bottom: 2px;\n"
"border-bottom-color: 2px solid rgba(46,82,101,200);\n"
"border-radius : 10px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(610, 390, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(610, 300, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(180, 430, 381, 101))
        self.label_6.setStyleSheet("color: rgb(243, 224, 9);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(270, 530, 191, 81))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_2.setText(_translate("Frame", "<html><head/><body><p><img src=\":/login/images.jpg\"/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/><br/></p></body></html>"))
        self.label_3.setText(_translate("Frame", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_commencer_login.setText(_translate("Frame", "commencer"))
        self.lineEdit_2.setPlaceholderText(_translate("Frame", "   player name"))
        self.lineEdit_3.setPlaceholderText(_translate("Frame", " password"))
        self.label_4.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">MOT DE PASSE :</span></p></body></html>"))
        self.label_5.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">NOM DU JOUEUR :</span></p></body></html>"))
        self.label_6.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:600; color:#d59a0f;\">BLOOMING</span></p></body></html>"))
        self.label_7.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:600; color:#d59a0f;\">GAME</span></p></body></html>"))
try :
        from model_cartes import ressourcelogin_rc
except:
        from vue.carte.model_cartes import ressourcelogin_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
