# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAINWINDOWS.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1389, 701)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, -30, 16777215, 16777215))
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-70, -20, 1621, 941))
        self.label.setStyleSheet("background-image: url(:/ressources/BACK.png);")
        self.label.setObjectName("label")
        self.pushButton_dashboard = QtWidgets.QPushButton(self.frame)
        self.pushButton_dashboard.setGeometry(QtCore.QRect(50, 40, 101, 23))
        self.pushButton_dashboard.setStyleSheet("QPushButton#pushButton_dashboard{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_dashboard:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_dashboard.setObjectName("pushButton_dashboard")
        self.pushButton_quitter = QtWidgets.QPushButton(self.frame)
        self.pushButton_quitter.setGeometry(QtCore.QRect(1110, 60, 75, 23))
        self.pushButton_quitter.setStyleSheet("QPushButton#pushButton_quitter{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_quitter:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_quitter.setObjectName("pushButton_quitter")
        self.label_40 = QtWidgets.QLabel(self.frame)
        self.label_40.setGeometry(QtCore.QRect(270, 100, 801, 531))
        self.label_40.setStyleSheet("background-image: url(:/ressources/taille.PNG);")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.Pion = QtWidgets.QPushButton(self.frame)
        self.Pion.setGeometry(QtCore.QRect(650, 570, 21, 21))
        self.Pion.setStyleSheet("background :  rgb(60, 44, 44);\n"
"border-radius : 10px")
        self.Pion.setText("")
        self.Pion.setObjectName("Pion")
        self.dashboard = QtWidgets.QFrame(self.frame)
        self.dashboard.setGeometry(QtCore.QRect(20, 70, 691, 621))
        self.dashboard.setStyleSheet("#dashboard{\n"
"\n"
"background : rgba(196, 209, 97, 0.8);\n"
"border-top-right-radius: 20px ;\n"
"border-top-left-radius: 20px ;\n"
"border-bottom-right-radius: 20px ;\n"
"border-bottom-left-radius: 20px ;\n"
"}\n"
"\n"
"QPushButton#pushButton_texte1:hover{\n"
"background : rgba(196, 209, 97, 0.8);\n"
"}\n"
"")
        self.dashboard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dashboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dashboard.setObjectName("dashboard")
        self.label_21 = QtWidgets.QLabel(self.dashboard)
        self.label_21.setGeometry(QtCore.QRect(20, 20, 311, 31))
        self.label_21.setStyleSheet("background : rgb(92, 53, 102);\n"
"border-top-left-radiust: 4px;\n"
"border-top-right-radiust: 4px;\n"
"color: white;\n"
"\n"
"QPushButton#pushButton_texte1{\n"
"background : rgb(92, 53, 102);\n"
"border-top-left-radiust: 4px;\n"
"border-top-right-radiust: 4px;\n"
"color: white;\n"
"    \n"
"    background-color: rgb(115, 218, 189);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_texte1:hover{\n"
"background : rgba(196, 209, 97, 0.8);\n"
"}\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.dashboard)
        self.label_22.setGeometry(QtCore.QRect(20, 230, 311, 31))
        self.label_22.setStyleSheet("background : rgb(92, 53, 102);\n"
"color: white;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.dashboard)
        self.label_23.setGeometry(QtCore.QRect(20, 430, 311, 31))
        self.label_23.setStyleSheet("background : rgb(92, 53, 102);\n"
"color: white;\n"
"text-align: center;")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.dashboard)
        self.label_24.setGeometry(QtCore.QRect(350, 430, 321, 31))
        self.label_24.setStyleSheet("background : rgb(92, 53, 102);\n"
"color: white;\n"
"text-align: center;")
        self.label_24.setObjectName("label_24")
        self.progressBar_2 = QtWidgets.QProgressBar(self.dashboard)
        self.progressBar_2.setGeometry(QtCore.QRect(370, 130, 291, 23))
        self.progressBar_2.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressBar_2.setStyleSheet("border-radius: 8px;")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_26 = QtWidgets.QLabel(self.dashboard)
        self.label_26.setGeometry(QtCore.QRect(380, 40, 231, 31))
        self.label_26.setStyleSheet("QPushButton#pushButton_dashboard{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_dashboard:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.text_revnu_passif_2 = QtWidgets.QLabel(self.dashboard)
        self.text_revnu_passif_2.setGeometry(QtCore.QRect(380, 160, 111, 17))
        self.text_revnu_passif_2.setObjectName("text_revnu_passif_2")
        self.label_27 = QtWidgets.QLabel(self.dashboard)
        self.label_27.setGeometry(QtCore.QRect(370, 270, 91, 31))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.dashboard)
        self.label_28.setGeometry(QtCore.QRect(380, 320, 101, 17))
        self.label_28.setObjectName("label_28")
        self.label_cash = QtWidgets.QLabel(self.dashboard)
        self.label_cash.setGeometry(QtCore.QRect(480, 270, 111, 31))
        self.label_cash.setWordWrap(True)
        self.label_cash.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.dashboard)
        self.label_30.setGeometry(QtCore.QRect(380, 340, 111, 17))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.dashboard)
        self.label_31.setGeometry(QtCore.QRect(380, 380, 91, 17))
        self.label_31.setObjectName("label_31")
        self.label_paycheck = QtWidgets.QLabel(self.dashboard)
        self.label_paycheck.setGeometry(QtCore.QRect(490, 380, 81, 20))
        self.label_paycheck.setWordWrap(True)
        self.label_paycheck.setObjectName("label_paycheck")
        self.label_totalentrees = QtWidgets.QLabel(self.dashboard)
        self.label_totalentrees.setGeometry(QtCore.QRect(490, 320, 81, 20))
        self.label_totalentrees.setWordWrap(True)
        self.label_totalentrees.setObjectName("label_totalentrees")
        self.label_depenses = QtWidgets.QLabel(self.dashboard)
        self.label_depenses.setGeometry(QtCore.QRect(490, 340, 91, 20))
        self.label_depenses.setWordWrap(True)
        self.label_depenses.setObjectName("label_depenses")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.dashboard)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 360, 271, 12))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(167772, 12))
        self.lineEdit_2.setStyleSheet("background : rgb(92, 53, 102)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.listWidget_entrees_2 = QtWidgets.QListWidget(self.dashboard)
        self.listWidget_entrees_2.setGeometry(QtCore.QRect(20, 50, 311, 161))
        self.listWidget_entrees_2.setStyleSheet("border-bottom: solid  10px red;\n"
"background-color: rgba(230, 214, 31, 0.6);\n"
"border-bottom-right-radius: 20px ;\n"
"border-bottom-left-radius: 20px ;\n"
"")
        self.listWidget_entrees_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget_entrees_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget_entrees_2.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget_entrees_2.setModelColumn(0)
        self.listWidget_entrees_2.setUniformItemSizes(True)
        self.listWidget_entrees_2.setObjectName("listWidget_entrees_2")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_entrees_2.addItem(item)
        self.listWidget_depenses_2 = QtWidgets.QListWidget(self.dashboard)
        self.listWidget_depenses_2.setGeometry(QtCore.QRect(20, 260, 311, 151))
        self.listWidget_depenses_2.setStyleSheet("border : none;\n"
"border-bottom-right-radius: 20px ;\n"
"background-color: rgba(251, 220, 255, 0.7);\n"
"border-bottom-left-radius: 20px ;")
        self.listWidget_depenses_2.setObjectName("listWidget_depenses_2")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_depenses_2.addItem(item)
        self.listWidget_investissements_2 = QtWidgets.QListWidget(self.dashboard)
        self.listWidget_investissements_2.setGeometry(QtCore.QRect(20, 460, 311, 151))
        self.listWidget_investissements_2.setStyleSheet("border-bottom-right-radius: 20px ;\n"
"background-color: rgb(202, 255, 185);\n"
"border:none;\n"
"border-bottom-left-radius: 20px ;")
        self.listWidget_investissements_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_investissements_2.setObjectName("listWidget_investissements_2")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_investissements_2.addItem(item)
        self.listWidget_responsabilites_2 = QtWidgets.QListWidget(self.dashboard)
        self.listWidget_responsabilites_2.setGeometry(QtCore.QRect(350, 460, 321, 151))
        self.listWidget_responsabilites_2.setStyleSheet("border-bottom-right-radius: 30px ; \n"
"border-bottom-left-radius: 30px ; \n"
"background-color: rgba(17, 255, 44, 0.6);")
        self.listWidget_responsabilites_2.setObjectName("listWidget_responsabilites_2")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_responsabilites_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_responsabilites_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_responsabilites_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_responsabilites_2.addItem(item)
        self.label_36 = QtWidgets.QLabel(self.dashboard)
        self.label_36.setGeometry(QtCore.QRect(590, 270, 71, 31))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.dashboard)
        self.label_37.setGeometry(QtCore.QRect(580, 320, 71, 21))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.dashboard)
        self.label_38.setGeometry(QtCore.QRect(580, 340, 47, 13))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.dashboard)
        self.label_39.setGeometry(QtCore.QRect(580, 380, 47, 13))
        self.label_39.setObjectName("label_39")
        self.label_32 = QtWidgets.QLabel(self.dashboard)
        self.label_32.setGeometry(QtCore.QRect(370, 20, 261, 31))
        self.label_32.setStyleSheet("color : black;")
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.pushButton_texte = QtWidgets.QPushButton(self.dashboard)
        self.pushButton_texte.setGeometry(QtCore.QRect(350, 20, 321, 61))
        self.pushButton_texte.setStyleSheet("QPushButton#pushButton_texte{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_texte:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_texte.setText("")
        self.pushButton_texte.setObjectName("pushButton_texte")
        self.pushButton_texte1 = QtWidgets.QPushButton(self.dashboard)
        self.pushButton_texte1.setGeometry(QtCore.QRect(360, 250, 311, 161))
        self.pushButton_texte1.setStyleSheet("QPushButton#pushButton_texte1{\n"
"    \n"
"    background-color: rgba(115, 218, 189, 0.8);\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_texte1:hover{\n"
"background : rgba(196, 209, 97, 0.8);\n"
"}\n"
"")
        self.pushButton_texte1.setText("")
        self.pushButton_texte1.setObjectName("pushButton_texte1")
        self.pushButton_texte2 = QtWidgets.QPushButton(self.dashboard)
        self.pushButton_texte2.setGeometry(QtCore.QRect(350, 100, 321, 101))
        self.pushButton_texte2.setStyleSheet("QPushButton#pushButton_texte2{\n"
"background-color: rgba(90, 153, 255, 0.7);\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_texte2:hover{\n"
"background : rgba(196, 209, 97, 0.8);\n"
"}\n"
"")
        self.pushButton_texte2.setText("")
        self.pushButton_texte2.setObjectName("pushButton_texte2")
        self.pushButton_texte2.raise_()
        self.pushButton_texte1.raise_()
        self.pushButton_texte.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.progressBar_2.raise_()
        self.label_26.raise_()
        self.text_revnu_passif_2.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_cash.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_paycheck.raise_()
        self.label_totalentrees.raise_()
        self.label_depenses.raise_()
        self.listWidget_entrees_2.raise_()
        self.listWidget_depenses_2.raise_()
        self.listWidget_investissements_2.raise_()
        self.listWidget_responsabilites_2.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.label_39.raise_()
        self.label_32.raise_()
        self.lineEdit_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1389, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_dashboard.setText(_translate("MainWindow", "DASHBOARD"))
        self.pushButton_quitter.setText(_translate("MainWindow", "QUITTER"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">entrees</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">dépenses</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px;text-align:center;  margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">investissements</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">resonsabilités</span></p></body></html>"))
        self.progressBar_2.setFormat(_translate("MainWindow", "%p%"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">et sortez de la rate race</span></p></body></html>"))
        self.text_revnu_passif_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">revenus passifs :</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">CASH :</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Total entrées :</span></p></body></html>"))
        self.label_cash.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">100000 </span></p><p><br/></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Total dépenses :</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "Cheque de paie :"))
        self.label_paycheck.setText(_translate("MainWindow", "<html><head/><body><p>12000</p></body></html>"))
        self.label_totalentrees.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">80000</span></p></body></html>"))
        self.label_depenses.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">10000</span></p></body></html>"))
        __sortingEnabled = self.listWidget_entrees_2.isSortingEnabled()
        self.listWidget_entrees_2.setSortingEnabled(False)
        item = self.listWidget_entrees_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget_entrees_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_depenses_2.isSortingEnabled()
        self.listWidget_depenses_2.setSortingEnabled(False)
        item = self.listWidget_depenses_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget_depenses_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_investissements_2.isSortingEnabled()
        self.listWidget_investissements_2.setSortingEnabled(False)
        item = self.listWidget_investissements_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget_investissements_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_responsabilites_2.isSortingEnabled()
        self.listWidget_responsabilites_2.setSortingEnabled(False)
        item = self.listWidget_responsabilites_2.item(0)
        item.setText(_translate("MainWindow", " New Item"))
        self.listWidget_responsabilites_2.setSortingEnabled(__sortingEnabled)
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">FCFA</span></p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">FCFA</span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">FCFA</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">FCFA</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">augmentez vos revenus passifs</span></p></body></html>"))

try :
        from model_cartes import backgroundimage_rc
except:
        from vue.carte.model_cartes import backgroundimage_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
