# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Marché.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(341, 354)
        Frame.setStyleSheet("\n"
"#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-radius:30px ;\n"
"}")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(110, 20, 141, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(0, 270, 371, 61))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_vendre_marche = QtWidgets.QPushButton(self.frame)
        self.pushButton_vendre_marche.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.pushButton_vendre_marche.setStyleSheet("QPushButton#pushButton_vendre_marche{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_vendre_marche:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_vendre_marche.setObjectName("pushButton_vendre_marche")
        self.pushButton_passer_marche = QtWidgets.QPushButton(self.frame)
        self.pushButton_passer_marche.setGeometry(QtCore.QRect(200, 20, 75, 23))
        self.pushButton_passer_marche.setStyleSheet("QPushButton#pushButton_passer_marche{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_passer_marche:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_passer_marche.setObjectName("pushButton_passer_marche")
        self.label_marche = QtWidgets.QLabel(Frame)
        self.label_marche.setGeometry(QtCore.QRect(36, 110, 231, 121))
        self.label_marche.setWordWrap(False)
        self.label_marche.setObjectName("label_marche")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 271, 161))
        self.label_2.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.label_marche.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:22pt;\">MARCHE</span></p></body></html>"))
        self.pushButton_vendre_marche.setText(_translate("Frame", "VENDRE"))
        self.pushButton_passer_marche.setText(_translate("Frame", "PASSER"))
        self.label_marche.setText(_translate("Frame", "marcche"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
