# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opportunite1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(365, 372)
        Frame.setStyleSheet("\n"
"#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-top-left-radius: 25px ;\n"
"border-top-right-radius: 25px ;\n"
"border-radius: 30px ;\n"
"}")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(70, 20, 251, 31))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_opportunite = QtWidgets.QLabel(Frame)
        self.label_opportunite.setGeometry(QtCore.QRect(50, 70, 271, 171))
        self.label_opportunite.setStyleSheet("border-radius: 30px ;")
        self.label_opportunite.setObjectName("label_opportunite")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-20, 280, 391, 61))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_grandes_opp = QtWidgets.QPushButton(self.frame)
        self.pushButton_grandes_opp.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.pushButton_grandes_opp.setStyleSheet("QPushButton#pushButton_grandes_opp{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_grandes_opp:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"\n"
"}\n"
"")
        self.pushButton_grandes_opp.setObjectName("pushButton_grandes_opp")
        self.pushButton_petites_opp = QtWidgets.QPushButton(self.frame)
        self.pushButton_petites_opp.setGeometry(QtCore.QRect(60, 20, 75, 23))
        self.pushButton_petites_opp.setStyleSheet("QPushButton#pushButton_petites_opp{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_petites_opp:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_petites_opp.setObjectName("pushButton_petites_opp")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 271, 181))
        self.label_2.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.label_opportunite.raise_()
        self.frame.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:22pt;\">OPPORTUNITE</span></p></body></html>"))
        self.label_opportunite.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">quelle type d\'opportunite voulez vous ?</span></p><p align=\"center\"><span style=\" font-weight:600;\">les petites opportunites ont </span></p><p align=\"center\"><span style=\" font-weight:600;\">un prix inferieur à 50000 FCFA</span></p><p align=\"center\"><span style=\" font-weight:600;\">les grandes opportunites ont </span></p><p align=\"center\"><span style=\" font-weight:600;\">un prix superieur à 600000 FCFA </span></p></body></html>"))
        self.pushButton_grandes_opp.setText(_translate("Frame", "GRANDES"))
        self.pushButton_petites_opp.setText(_translate("Frame", "PETITES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
