# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opportunite2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(377, 352)
        Frame.setMinimumSize(QtCore.QSize(0, 0))
        Frame.setStyleSheet("\n"
"#Frame{\n"
"background : rgb(196, 209, 97);\n"
"border-radius: 30px ;\n"
"}")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(60, 10, 221, 41))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.label_opportunite2 = QtWidgets.QLabel(Frame)
        self.label_opportunite2.setGeometry(QtCore.QRect(29, 74, 281, 91))
        self.label_opportunite2.setWordWrap(True)
        self.label_opportunite2.setObjectName("label_opportunite2")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-110, 270, 571, 51))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_payer_opp = QtWidgets.QPushButton(self.frame)
        self.pushButton_payer_opp.setGeometry(QtCore.QRect(160, 10, 75, 23))
        self.pushButton_payer_opp.setStyleSheet("QPushButton#pushButton_payer_opp{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_payer_opp:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_payer_opp.setObjectName("pushButton_payer_opp")
        self.pushButton_passer_opp = QtWidgets.QPushButton(self.frame)
        self.pushButton_passer_opp.setGeometry(QtCore.QRect(360, 10, 75, 23))
        self.pushButton_passer_opp.setStyleSheet("QPushButton#pushButton_passer_opp{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_passer_opp:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}\n"
"")
        self.pushButton_passer_opp.setObjectName("pushButton_passer_opp")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(60, 190, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(60, 210, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_cout_opp2 = QtWidgets.QLabel(Frame)
        self.label_cout_opp2.setGeometry(QtCore.QRect(220, 170, 101, 20))
        self.label_cout_opp2.setObjectName("label_cout_opp2")
        self.label_prixmarche_opp2 = QtWidgets.QLabel(Frame)
        self.label_prixmarche_opp2.setGeometry(QtCore.QRect(220, 190, 101, 21))
        self.label_prixmarche_opp2.setObjectName("label_prixmarche_opp2")
        self.label_cashflow = QtWidgets.QLabel(Frame)
        self.label_cashflow.setGeometry(QtCore.QRect(220, 210, 101, 21))
        self.label_cashflow.setObjectName("label_cashflow")
        self.label_marche = QtWidgets.QLabel(Frame)
        self.label_marche.setGeometry(QtCore.QRect(20, 60, 331, 191))
        self.label_marche.setStyleSheet("border-radius: 40px;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_marche.setText("")
        self.label_marche.setObjectName("label_marche")
        self.label_marche.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.label_opportunite2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_cout_opp2.raise_()
        self.label_prixmarche_opp2.raise_()
        self.label_cashflow.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:22pt;\">OPPORTUNITE</span></p></body></html>"))
        self.label_opportunite2.setText(_translate("Frame", "opportunité"))
        self.pushButton_payer_opp.setText(_translate("Frame", "PAYER"))
        self.pushButton_passer_opp.setText(_translate("Frame", "PASSER"))
        self.label_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">cout : </span></p></body></html>"))
        self.label_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">prix sur le marche :</span></p></body></html>"))
        self.label_4.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">cashflow :</span></p></body></html>"))
        self.label_cout_opp2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">100 000</span></p></body></html>"))
        self.label_prixmarche_opp2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">0 - 200000</span></p></body></html>"))
        self.label_cashflow.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-weight:600;\">5000</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
