# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pret_pour_paie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(338, 354)
        Frame.setStyleSheet("#Frame{\n"
"background-color: rgba(196, 209, 97, 1);\n"
"border-top-right-radius: 20px ;\n"
"border-top-left-radius: 20px ;\n"
"border-bottom-right-radius: 20px ;\n"
"border-bottom-left-radius: 20px ;\n"
"}")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(-10, 0, 351, 61))
        self.label.setStyleSheet("color : rgb(45, 111, 47);\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(-50, 260, 441, 51))
        self.frame.setStyleSheet("background-color:rgba(34, 255, 23, 0.5);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_passer_emprunt = QtWidgets.QPushButton(self.frame)
        self.pushButton_passer_emprunt.setGeometry(QtCore.QRect(280, 10, 81, 21))
        self.pushButton_passer_emprunt.setStyleSheet("QPushButton#pushButton_passer_emprunt{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_passer_emprunt:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_passer_emprunt.setObjectName("pushButton_passer_emprunt")
        self.pushButton_emprunt_pour_achat = QtWidgets.QPushButton(self.frame)
        self.pushButton_emprunt_pour_achat.setGeometry(QtCore.QRect(90, 10, 81, 21))
        self.pushButton_emprunt_pour_achat.setStyleSheet("QPushButton#pushButton_emprunt_pour_achat{\n"
"    background-color: rgb(23,100,19);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_emprunt_pour_achat:hover{\n"
"background-color: rgb(27, 27, 27);\n"
"}")
        self.pushButton_emprunt_pour_achat.setObjectName("pushButton_emprunt_pour_achat")
        self.label_rolldice = QtWidgets.QLabel(Frame)
        self.label_rolldice.setGeometry(QtCore.QRect(20, 120, 291, 61))
        self.label_rolldice.setStyleSheet("font: 8pt \"MS Sans Serif\";")
        self.label_rolldice.setObjectName("label_rolldice")
        self.label_somme_pret = QtWidgets.QLabel(Frame)
        self.label_somme_pret.setGeometry(QtCore.QRect(90, 190, 101, 31))
        self.label_somme_pret.setObjectName("label_somme_pret")
        self.label_somme_unite = QtWidgets.QLabel(Frame)
        self.label_somme_unite.setGeometry(QtCore.QRect(190, 190, 81, 31))
        self.label_somme_unite.setObjectName("label_somme_unite")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 251, 161))
        self.label_2.setStyleSheet("border-radius : 40px ;\n"
"background-color:rgba(34, 255, 23, 0.5);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.label_rolldice.raise_()
        self.label_somme_pret.raise_()
        self.label_somme_unite.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">EMPRUNTER</span></p></body></html>"))
        self.pushButton_passer_emprunt.setText(_translate("Frame", "passer"))
        self.pushButton_emprunt_pour_achat.setText(_translate("Frame", "emprunter"))
        self.label_rolldice.setText(_translate("Frame", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">vous n\'avez pas assez de </span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">cash faites un pret de :</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\"><br/></span></p></body></html>"))
        self.label_somme_pret.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">10000</span></p></body></html>"))
        self.label_somme_unite.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">FCFA</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
