# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inter_cash1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1091, 701))
        #self.label.setStyleSheet("QFrame{\n""background-color:green;\n""}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("vue/imcash.png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 350, 21, 21))
        self.pushButton.setStyleSheet("border-radius : 10px;\n"
"background : green;\n"
"")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget,clicked = self.deplace)
        self.pushButton_14.setGeometry(QtCore.QRect(790, 540, 151, 25))
        self.pushButton_14.setObjectName("pushButton_14")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def __init__(self):
            self.liste_coord = [(450,330,21,21),(480,310,21,21),(510,300,21,21),(540,300,21,21),(580,310,21,21),
                           (610,320,21,21),(640,350,21,21),(660,380,21,21),(670,410,21,21),(670,450,21,21),
                           (660,490,21,21),(640,520,21,21),(620,540,21,21),(400,480,21,21),(390,450,21,21),
                           (390,420,21,21),(400,380,21,21)]
            self.num_posi = 0
    
    def deplace(self):
        self.pushButton.setGeometry(QtCore.QRect(self.liste_coord[self.num_posi][0],self.liste_coord[self.num_posi][1],self.liste_coord[self.num_posi][2],self.liste_coord[self.num_posi][3]))
        if self.num_posi < len(self.liste_coord)-1:
                self.num_posi += 1
        else:
                self.num_posi = 0
              

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_14.setText(_translate("MainWindow", "deplace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

